defaults:
  - _self_

default_role:
  trainable: false
  act_by_user: false
  model:
    url:  # Will be read from OPENAI_BASE_URL environment variable
    api_key:  # Will be read from OPENAI_API_KEY environment variable
    model_name: qwen-plus
    temperature: 0.7
    max_tokens: 2048
    stream: false
  agent:
    type: ThinkingReActAgent
    kwargs: {} 


portraits:
  1:
    name: Agent1
    model:
      model_name: qwen-max
  
  2:
    name: Agent2
  
  3:
    name: Agent3
  
  4:
    name: Agent4
    model:
      model_name: qwen3-30b-a3b-instruct-2507
  
  5:
    name: Agent5
  
  6:
    name: Agent6

  7:
    name: Agent7
    model:
      model_name: qwen2.5-32b-instruct
  
  8:
    name: Agent8
  
  9:
    name: Agent9
  
  10:
    name: Agent10
  
  11:
    name: Agent11
    model:
      model_name: qwen-max
  
  12:
    name: Agent12
    model:
      model_name: qwen-turbo
  
  13:
    name: Agent13
  
  14:
    name: Agent14
  
  15:
    name: Agent15